In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics
from sklearn import preprocessing

In [2]:
df = pd.read_csv("Life_Expectancy.csv")

In [3]:
df.head()

,Country,Status,Adult_Mortality,Infant_Deaths,Hepatitis,Measles,BMI,Underfive_Deaths,Polio,Diphtheria,HIV,GDP,Population,Malnourished10_19,Malnourished5_9,Income_Index,Schooling,Expected
0,Afghanistan,Developing,263,62,65,1154,19.1,83,6,65,0.1,584.259210,33736494,17.2,17.3,0.479,10.1,65.0
1,Albania,Developing,8,0,98,0,57.2,1,98,98,0.1,4575.763787,288914,1.2,1.3,0.761,14.2,77.5
2,Algeria,Developing,19,21,95,63,59.5,24,95,95,0.1,4132.762920,39871528,6.0,5.8,0.743,14.4,75.6
3,Angola,Developing,335,66,64,118,23.3,98,7,64,1.9,3695.793748,2785935,8.3,8.2,0.531,11.4,52.4
4,Argentina,Developing,116,8,94,0,62.8,9,93,94,0.1,13467.123600,43417765,1.0,0.9,0.826,17.3,76.3

In [4]:
# deleting the non numeric values
df = df.drop(['Country','Status'], axis=1)

In [5]:
df.head()

,Adult_Mortality,Infant_Deaths,Hepatitis,Measles,BMI,Underfive_Deaths,Polio,Diphtheria,HIV,GDP,Population,Malnourished10_19,Malnourished5_9,Income_Index,Schooling,Expected
0,263,62,65,1154,19.1,83,6,65,0.1,584.259210,33736494,17.2,17.3,0.479,10.1,65.0
1,8,0,98,0,57.2,1,98,98,0.1,4575.763787,288914,1.2,1.3,0.761,14.2,77.5
2,19,21,95,63,59.5,24,95,95,0.1,4132.762920,39871528,6.0,5.8,0.743,14.4,75.6
3,335,66,64,118,23.3,98,7,64,1.9,3695.793748,2785935,8.3,8.2,0.531,11.4,52.4
4,116,8,94,0,62.8,9,93,94,0.1,13467.123600,43417765,1.0,0.9,0.826,17.3,76.3

In [6]:
y = df['Expected'].values
x = df.drop(['Expected'],axis = 1).values

In [7]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [8]:
scaler = preprocessing.StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.fit_transform(x_test)

In [9]:
model = LinearRegression()

In [10]:
model.fit(x_train,y_train)

LinearRegression()

In [11]:
y_pred = model.predict(x_test)
x_pred = model.predict(x_train)

In [12]:
print("Prediction for test set: {}".format(y_pred))

Prediction for test set: [66.74389456 78.09235413 69.11084607 64.00171485 64.60581051 77.43410476
 80.12891056 48.58868706 59.27437772 76.08327078 72.98877818 69.62952848
 78.19677975 72.19847117 74.95128736 81.78230233 68.19007372 70.3868525
 75.74631404 62.41136826 67.42762894 79.67688669 57.94433164 77.63372572
 76.1656396 ]

In [13]:
mlr_diff = pd.DataFrame({'Actual value': y_test, 'Predicted value': y_pred})
mlr_diff

    Actual value  Predicted value
0           65.7        66.743895
1           82.4        78.092354
2           79.0        69.110846
3           69.2        64.001715
4           69.1        64.605811
5           81.1        77.434105
6           81.4        80.128911
7           57.0        48.588687
8           52.0        59.274378
9           76.3        76.083271
10          76.1        72.988778
11          67.3        69.629528
12          81.0        78.196780
13          70.0        72.198471
14          75.0        74.951287
15          81.9        81.782302
16          71.8        68.190074
17          67.5        70.386853
18          75.5        75.746314
19          63.8        62.411368
20          71.9        67.427629
21          81.6        79.676887
22          65.0        57.944332
23          85.0        77.633726
24          78.0        76.165640

In [14]:
meanAbErr = metrics.mean_absolute_error(y_test, y_pred)
meanSqErr = metrics.mean_squared_error(y_test, y_pred)
rootMeanSqErr = np.sqrt(metrics.mean_squared_error(y_test, y_pred))

print('Mean Absolute Error:', meanAbErr)
print('Mean Square Error:', meanSqErr)
print('Root Mean Square Error:', rootMeanSqErr)

Mean Absolute Error: 3.4865975029472174
Mean Square Error: 19.428287517561113
Root Mean Square Error: 4.407753114406604

In [15]:
metrics.r2_score(y_test,y_pred)

0.710959737567568